//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public int id { get; set; }
        public string todo_text { get; set; }
        public Nullable<bool> completed { get; set; }
        public Nullable<System.DateTime> completed_at { get; set; }
    }
}
